language: python

install:
- pip install -r test_requirements.txt
- pip install -r requirements.txt
- pip install bumpversion twine
stages:
- test
- name: coverage
- name: merge
- name: deploy

script:
  - python setup.py pytest

cache:
  - pip: true

jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7-dev
    - stage: coverage
      python: 3.6
      script:
        - codecov
    - stage: merge
      python: 3.6
      script:
        - "git clone https://gist.github.com/2c04596a45ccac57fe8dde0718ad58ee.git /tmp/travis-automerge"
        - "chmod a+x /tmp/travis-automerge/auto_merge_travis_with_bumpversion.sh"
        - "BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=master /tmp/travis-automerge/auto_merge_travis_with_bumpversion.sh"
    - stage: deploy
      python:
        - 3.6
        - 2.7
      script: 
        - "git clone https://gist.github.com/cf9b261f26a1bf3fae6b59e7047f007a.git /tmp/travis-autodist"
        - "chmod a+x /tmp/travis-autodist/pypi_dist.sh"
        - "BRANCHES_TO_DIST='master' /tmp/travis-autodist/pypi_dist.sh"